services:
  mavendata:
    image: prashanthnagonde/maven-web-app:5
    restart: always
    ports:
    - 8303:8080
    networks:
    - mavenpackbridge
networks:
  mavenpackbridge:
    driver: bridge
volumes:
  mavenpackvol:
    driver: local
